"""Initial recognition and HITL schema"""

from alembic import op
import sqlalchemy as sa

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dataset_versions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.String(length=100), nullable=False),
        sa.Column("category", sa.String(length=30), nullable=False),
        sa.Column("split", sa.String(length=20), nullable=False),
        sa.Column("privacy", sa.String(length=20), nullable=False),
        sa.Column("directory", sa.Text(), nullable=False),
        sa.Column("manifest_sha256", sa.String(length=64), nullable=False),
        sa.Column("sample_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("version"),
    )
    op.create_table(
        "recognition_jobs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("scope", sa.String(length=20), nullable=False),
        sa.Column("original_path", sa.Text(), nullable=False),
        sa.Column("original_sha256", sa.String(length=64), nullable=False),
        sa.Column("mime_type", sa.String(length=40), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column("image_difficulty", sa.String(length=20), nullable=False),
        sa.Column("scenario_tags", sa.JSON(), nullable=False),
        sa.Column("group_key", sa.String(length=200), nullable=False),
        sa.Column("privacy", sa.String(length=20), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("recognition_jobs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_recognition_jobs_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_recognition_jobs_group_key"), ["group_key"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_recognition_jobs_original_sha256"), ["original_sha256"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_recognition_jobs_scope"), ["scope"], unique=False)

    op.create_table(
        "benchmark_experiments",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("dataset_id", sa.String(length=36), nullable=False),
        sa.Column("targets", sa.JSON(), nullable=False),
        sa.Column("evaluation_version", sa.String(length=60), nullable=False),
        sa.Column("regression_policy", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["dataset_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "dataset_items",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("dataset_id", sa.String(length=36), nullable=False),
        sa.Column("source_job_id", sa.String(length=36), nullable=False),
        sa.Column("group_key", sa.String(length=200), nullable=False),
        sa.Column("image_sha256", sa.String(length=64), nullable=False),
        sa.Column("split", sa.String(length=20), nullable=False),
        sa.Column("snapshot", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["dataset_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_job_id"],
            ["recognition_jobs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("dataset_items", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_dataset_items_dataset_id"), ["dataset_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_dataset_items_group_key"), ["group_key"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_dataset_items_image_sha256"), ["image_sha256"], unique=False
        )

    op.create_table(
        "recognition_attempts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("job_id", sa.String(length=36), nullable=False),
        sa.Column("profile_id", sa.String(length=100), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("model", sa.Text(), nullable=False),
        sa.Column("model_version", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("snapshot", sa.JSON(), nullable=False),
        sa.Column("processed_path", sa.Text(), nullable=True),
        sa.Column("processed_sha256", sa.String(length=64), nullable=True),
        sa.Column("normalized_ai_result", sa.JSON(), nullable=True),
        sa.Column("validation_result", sa.JSON(), nullable=False),
        sa.Column("decision_result", sa.JSON(), nullable=True),
        sa.Column("repair_result", sa.JSON(), nullable=True),
        sa.Column("error_code", sa.String(length=50), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("latency_ms", sa.Float(), nullable=True),
        sa.Column("processing_ms", sa.Float(), nullable=True),
        sa.Column("queue_ms", sa.Float(), nullable=True),
        sa.Column("hard_reasons", sa.JSON(), nullable=False),
        sa.Column("worker_id", sa.String(length=36), nullable=True),
        sa.Column("lease_until", sa.Float(), nullable=True),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.Column("started_at", sa.String(length=40), nullable=True),
        sa.Column("finished_at", sa.String(length=40), nullable=True),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["recognition_jobs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("recognition_attempts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_recognition_attempts_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_recognition_attempts_job_id"), ["job_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_recognition_attempts_provider"), ["provider"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_recognition_attempts_status"), ["status"], unique=False
        )

    op.create_table(
        "benchmark_items",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("benchmark_id", sa.String(length=36), nullable=False),
        sa.Column("dataset_item_id", sa.String(length=36), nullable=False),
        sa.Column("attempt_id", sa.String(length=36), nullable=False),
        sa.Column("target_id", sa.String(length=100), nullable=False),
        sa.Column("ground_truth_snapshot", sa.JSON(), nullable=False),
        sa.Column("field_assessments", sa.JSON(), nullable=False),
        sa.Column("assessment_history", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["attempt_id"],
            ["recognition_attempts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["benchmark_id"],
            ["benchmark_experiments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["dataset_item_id"],
            ["dataset_items.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("attempt_id"),
    )
    with op.batch_alter_table("benchmark_items", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_benchmark_items_benchmark_id"), ["benchmark_id"], unique=False
        )

    op.create_table(
        "confirmation_revisions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("job_id", sa.String(length=36), nullable=False),
        sa.Column("attempt_id", sa.String(length=36), nullable=False),
        sa.Column("revision_no", sa.Integer(), nullable=False),
        sa.Column("previous_revision_id", sa.String(length=36), nullable=True),
        sa.Column("human_ground_truth", sa.JSON(), nullable=False),
        sa.Column("validation_result", sa.JSON(), nullable=False),
        sa.Column("review_active_ms", sa.Integer(), nullable=False),
        sa.Column("confirmed_at", sa.String(length=40), nullable=False),
        sa.ForeignKeyConstraint(
            ["attempt_id"],
            ["recognition_attempts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["recognition_jobs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["previous_revision_id"],
            ["confirmation_revisions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("job_id", "revision_no"),
    )
    with op.batch_alter_table("confirmation_revisions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_confirmation_revisions_attempt_id"), ["attempt_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_confirmation_revisions_job_id"), ["job_id"], unique=False
        )

    op.create_table(
        "machine_observations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("attempt_id", sa.String(length=36), nullable=False),
        sa.Column("stage", sa.String(length=20), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("model", sa.Text(), nullable=False),
        sa.Column("model_version", sa.Text(), nullable=True),
        sa.Column("raw_result", sa.JSON(), nullable=True),
        sa.Column("output_text", sa.Text(), nullable=True),
        sa.Column("confidence_kind", sa.String(length=40), nullable=False),
        sa.Column("calibration_version", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.ForeignKeyConstraint(
            ["attempt_id"],
            ["recognition_attempts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("machine_observations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_machine_observations_attempt_id"), ["attempt_id"], unique=False
        )

    op.create_table(
        "field_annotations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("confirmation_id", sa.String(length=36), nullable=False),
        sa.Column("field_name", sa.String(length=60), nullable=False),
        sa.Column("ai_value", sa.JSON(), nullable=True),
        sa.Column("human_value", sa.JSON(), nullable=True),
        sa.Column("human_input", sa.JSON(), nullable=True),
        sa.Column("before_value", sa.JSON(), nullable=True),
        sa.Column("ai_confidence", sa.String(length=20), nullable=False),
        sa.Column("validation_warning", sa.JSON(), nullable=False),
        sa.Column("was_corrected", sa.Boolean(), nullable=False),
        sa.Column("correction_type", sa.String(length=40), nullable=False),
        sa.Column("correction_type_source", sa.String(length=20), nullable=False),
        sa.Column("annotation_status", sa.String(length=20), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["confirmation_id"],
            ["confirmation_revisions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("confirmation_id", "field_name"),
    )
    with op.batch_alter_table("field_annotations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_field_annotations_confirmation_id"), ["confirmation_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_field_annotations_field_name"), ["field_name"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("field_annotations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_field_annotations_field_name"))
        batch_op.drop_index(batch_op.f("ix_field_annotations_confirmation_id"))

    op.drop_table("field_annotations")
    with op.batch_alter_table("machine_observations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_machine_observations_attempt_id"))

    op.drop_table("machine_observations")
    with op.batch_alter_table("confirmation_revisions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_confirmation_revisions_job_id"))
        batch_op.drop_index(batch_op.f("ix_confirmation_revisions_attempt_id"))

    op.drop_table("confirmation_revisions")
    with op.batch_alter_table("benchmark_items", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_benchmark_items_benchmark_id"))

    op.drop_table("benchmark_items")
    with op.batch_alter_table("recognition_attempts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_recognition_attempts_status"))
        batch_op.drop_index(batch_op.f("ix_recognition_attempts_provider"))
        batch_op.drop_index(batch_op.f("ix_recognition_attempts_job_id"))
        batch_op.drop_index(batch_op.f("ix_recognition_attempts_created_at"))

    op.drop_table("recognition_attempts")
    with op.batch_alter_table("dataset_items", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_dataset_items_image_sha256"))
        batch_op.drop_index(batch_op.f("ix_dataset_items_group_key"))
        batch_op.drop_index(batch_op.f("ix_dataset_items_dataset_id"))

    op.drop_table("dataset_items")
    op.drop_table("benchmark_experiments")
    with op.batch_alter_table("recognition_jobs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_recognition_jobs_scope"))
        batch_op.drop_index(batch_op.f("ix_recognition_jobs_original_sha256"))
        batch_op.drop_index(batch_op.f("ix_recognition_jobs_group_key"))
        batch_op.drop_index(batch_op.f("ix_recognition_jobs_created_at"))

    op.drop_table("recognition_jobs")
    op.drop_table("dataset_versions")
    # ### end Alembic commands ###
